# Default values for exa-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "default"  # replace with non-default namespace name if needed
volumeNamePrefix: "pvc-exa"

replicaCount: 1

image:
  repository: "image-registry.openshift-image-registry.svc:5000/openshift-kmm/exascaler-csi-file-driver"
  pullPolicy: "IfNotPresent"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "vES-587"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

secretName: exascaler-csi-file-driver-config
