kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exascaler-csi-privileged-scc-binding
subjects:
  - kind: ServiceAccount
    name: exascaler-csi-driver-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: exascaler-csi-privileged-scc-role
