
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: driver-role-binding
subjects:
  - kind: ServiceAccount
    name: exascaler-csi-driver-service-account
    namespace: openshift-operators
roleRef:
  kind: ClusterRole
  name: driver-cluster-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resizer-binding
subjects:
  - kind: ServiceAccount
    name: exascaler-csi-driver-service-account
    namespace: openshift-operators
roleRef:
  kind: ClusterRole
  name: csi-resizer-role
  apiGroup: rbac.authorization.k8s.io


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resizer-role-cfg
subjects:
  - kind: ServiceAccount
    name: exascaler-csi-driver-service-account
    namespace: openshift-operators
roleRef:
  kind: Role
  name: external-resizer-cfg
  apiGroup: rbac.authorization.k8s.io
